# Generated by Django 4.2.5 on 2023-10-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0003_remove_labgroups_is_visible_labgroups_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
    ]
