# Generated by Django 4.2.5 on 2023-11-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0018_merge_0017_labgroups_assistant_0017_labgroups_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(default=0),
        ),
    ]
