# Generated by Django 4.2.5 on 2023-11-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0022_user_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
    ]
