# Generated by Django 4.2.5 on 2023-11-15 19:16

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0023_remove_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=django_cryptography.fields.encrypt(models.CharField(default='000000000')),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, unique=True)),
        ),
    ]
