# Generated by Django 4.2.5 on 2024-11-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0027_user_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
