# Generated by Django 4.2.5 on 2023-11-16 12:14

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0029_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
