name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Service for Postgres DB
    services:
      postgres:
        image: postgres:latest
        env:
          NAME: github_actions
          USER: postgres
          PASSWORD: postgres
          HOST: 127.0.0.1
          PORT: 5432
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install Poetry
      - name: Install Poetry
        run: pip3 install poetry
  
      # Install dependencies
      - name: Install dependencies
        run: poetry install
      
      # Run Migrations
      - name: Run migrations
        run: python manage.py migrate

      # Run tests
      - name: Run tests
        run: poetry run python app/manage.py test ilmoweb
      
      # Run Pylint
      - name: Lint
        run: poetry run pylint app/ilmoweb/
