name: publish_main

on:
  workflow_dispatch:
    branches:
      - 'main'

#  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Build docker image and push it to Docker Hub
    - name: Build image
      run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/ilmoweb:ilmo

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ilmoweb:ilmo
